# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=b'Like'),
        ),
    ]
