# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171116_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.URLField(blank=True, default=b''),
        ),
    ]
