# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20171116_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(related_name='subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
