# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171119_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=b'image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
