# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171119_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(upload_to=b'pic_folder'),
        ),
    ]
