# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171119_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(help_text=b'150x150px', upload_to=b'images/', verbose_name='Photo'),
        ),
    ]
