# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, help_text=b'150x150px', upload_to=b'pic_folder', verbose_name='Photo'),
        ),
    ]
