# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171119_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, help_text=b'150x150px', null=True, upload_to=b'', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(blank=True, help_text=b'150x150px', upload_to=b'', verbose_name='profoto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
