# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20171121_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedone',
            field=models.ManyToManyField(blank=True, related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
