# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20171121_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postpicurl',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
