# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20171121_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
