# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_auto_20171122_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='coments', to=settings.AUTH_USER_MODEL),
        ),
    ]
