# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20171125_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
