# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20171125_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(blank=True, default=b'http://res.cloudinary.com/dwdm42giw/image/upload/v1511185812/default_profile_picture_kocxfz.png', upload_to=b'profilepics/', verbose_name='profoto'),
        ),
    ]
